/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { openDB } from 'idb';

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// Suppress Cache.put network errors caused by self-signed certs in local network testing
self.addEventListener('unhandledrejection', (event) => {
  if (event.reason && event.reason.message && event.reason.message.includes('Cache.put')) {
    event.preventDefault();
  }
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Setup IndexedDB for shared files
const initDB = async () => {
  return openDB('ShareTargetDB', 1, {
    upgrade(db) {
      db.createObjectStore('shared_files', { keyPath: 'id', autoIncrement: true });
    }
  });
};

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Intercept the Web Share Target POST request
  if (event.request.method === 'POST' && url.pathname === '/share-receive') {
    event.respondWith((async () => {
      try {
        const formData = await event.request.formData();
        const mediaFiles = formData.getAll('media');
        const title = formData.get('title') || '';
        const text = formData.get('text') || '';
        const sharedUrl = formData.get('url') || '';

        const db = await initDB();
        const tx = db.transaction('shared_files', 'readwrite');
        const store = tx.objectStore('shared_files');
        
        await store.put({
          title,
          text,
          url: sharedUrl,
          files: mediaFiles,
          timestamp: Date.now()
        });
        
        await tx.done;

        // Redirect back to the app with a query parameter
        return Response.redirect('/?shared=true', 303);
      } catch (error) {
        console.error('Error handling share target POST:', error);
        return Response.redirect('/?shared=error', 303);
      }
    })());
  }
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
